name: file-size-impact

on: pull_request_target

jobs:
  file-size-impact:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.9.1]
    runs-on: ${{ matrix.os }}
    name: report file size impact
    steps:
      - name: Setup git
        uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.0
      - name: pnpm install
        run: pnpm install --frozen-lockfile
      - name: pnpm run build
        run: pnpm run build
      - name: pnpm install jsenv-file-size
        run: pnpm install --prefix ./.github/workflows/file-size-impact/
      - name: Report file size impact
        run: node ./.github/workflows/file-size-impact/report-file-size-impact.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
